name: Reusable deploy workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: Nsme of the artifact files
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List files
        run: ls -ltr
      - name: Output information
        run: echo "Deploying and uploading....."